// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Configuración automática generada por FlutterFire CLI para conectar con Firebase.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    // Selecciona las credenciales adecuadas según el sistema operativo del dispositivo
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Credenciales específicas para la plataforma Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiHavzvlkrX3tMnoKETqaEqFi-CzhFu38',
    appId: '1:822029900467:android:1cea3a65fafecd57bd2ec6',
    messagingSenderId: '822029900467',
    projectId: 'chronarc-8c034',
    storageBucket: 'chronarc-8c034.firebasestorage.app',
  );

  // Credenciales específicas para la plataforma iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaE8lLgSAqvZXIPpkCDMnozfiQd4BprgM',
    appId: '1:822029900467:ios:486a4e9b94236a6fbd2ec6',
    messagingSenderId: '822029900467',
    projectId: 'chronarc-8c034',
    storageBucket: 'chronarc-8c034.firebasestorage.app',
    iosBundleId: 'com.example.chronarc',
  );
}